#######
#
# documentation-template
# bootstrap template for Jekyll with GitHub Pages based upon thecdil/bootstrap-template
# This template will contain any common bootstrap components, page layouts and any other
# assets intended for use accross multiple elizium documentation projects.
# https://github.com/EliziumNet/documentation-template
#
#######

#######
# SITE SETTINGS
#
title: elizium-documentation-template
description: "Bootstrap documentation template intended for documentation of Elizium projects"
year: 2021
author: plastikfan
# add search box to navbar, true/false
search: true

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# use url for the domain, e.g. https://thecdil.github.io
# on gh-pages follow the pattern: https://username.github.io
url: https://EliziumNet.github.io
# use baseurl to add subsection of the domain, e.g. /timelinejs-template
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl: /documentation-template
# location of code, the full url to your github repository
source-code: https://github.com/EliziumNet/documentation-template

##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id:

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter,
# all files in the "pages" folder will be output at root of site
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext

# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
